[tool.poetry]
name = "banedetta_mfb"
version = "1"
description = ".."
authors = ["Taskov1ch"]

[tool.poetry.dependencies]
python = "^3.10"
aiomysql = "^0.2.0"
cryptography = "^43.0.1"
asyncio = "^3.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
